FROM node:10

WORKDIR /app

#RUN pm2 install typescript
#RUN pm2 install @types/node


EXPOSE 5000

COPY package.json /app
RUN npm install
RUN npm install pm2

# Set the default command to run when a container starts
CMD ["npm","run","start:dev"]

COPY . /app

