query me{
    me{
        success
        errors{
            path
            message
        }
        data{
            id
            email
            avatar
            emailVerified
            twoFactorVerified
            balance
            phoneNumberVerified
            phoneNumber
            password
            firstName
            lastName
            defaultCurrency
            forgotPasswordLock
            name
        }
    }
}