version: "3.7"

services:
  redis:
    container_name: "redis"
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - 6379:6379
    expose:
      - 6379

  account:
    image: account
    depends_on:
      - redis
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
    ports:
      - 3001:3001

  bank:
    image: bank
    depends_on:
      - redis
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
    ports:
      - 3002:3002

  transfer:
    image: transfer
    depends_on:
      - redis
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
    ports:
      - 3004:3004

  lnd:
    image: lnd
    depends_on:
      - redis
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
    ports:
      - 3003:3003

  # gateway:
  #   image: gateway
  #   depends_on:
  #     - redis
  #     - account
  #     - bank
  #     - transfer
  #     - lnd
  #   environment:
  #     NODE_ENV: development
  #     REDIS_HOST: redis
  #   ports:
  #     - 3000:3000
