query _entities($representations: [_Any!]!){
    _entities(representations: $representations){
        ... on WalletSchema {
            id
            userId
            balance
            defaultCurrency
            transactions{
                id
                fromWalletId
                toWalletId
                amount
                networkFee
                transactionFee
                status
                description
                method
                currency
                btcExchangeRate
                btcAmount
                createdAt
            }
            createdAt
        }
        ... on TransactionSchema {
            id
            fromWalletId
            toWalletId
            amount
            networkFee
            transactionFee
            status
            description
            method
            currency
            btcExchangeRate
            btcAmount
            createdAt
        }
        ... on TransactionRequestSchema {
            id
            transaction{
                id
                fromWalletId
                toWalletId
                amount
                networkFee
                transactionFee
                status
                description
                method
                currency
                btcExchangeRate
                btcAmount
                createdAt
            }
            requestFrom
            requestTo
        }
    }
}