query getWallet($data: GetWalletDto!){
    getWallet(data: $data){
        success
        errors{
            path
            message
        }
        data{
            id
            userId
            balance
            defaultCurrency
            transactions{
                id
                fromWalletId
                toWalletId
                amount
                networkFee
                transactionFee
                status
                description
                method
                currency
                btcExchangeRate
                btcAmount
                createdAt
            }
            createdAt
        }
    }
}