query getUsers($Pagination: PaginationInputType){
    getUsers(Pagination: $Pagination){
        success
        errors{
            path
            message
        }
        data{
            id
            email
            avatar
            emailVerified
            twoFactorVerified
            phoneNumberVerified
            phoneNumber
            firstName
            lastName
            forgotPasswordLock
            contacts{
                id
                email
                avatar
                emailVerified
                twoFactorVerified
                phoneNumberVerified
                phoneNumber
                firstName
                lastName
                forgotPasswordLock
                contacts{
                    id
                    email
                    avatar
                    emailVerified
                    twoFactorVerified
                    phoneNumberVerified
                    phoneNumber
                    firstName
                    lastName
                    forgotPasswordLock
                    createdAt
                    name
                }
                createdAt
                name
            }
            createdAt
            name
        }
    }
}