version:            '3.7'

services:
  redis:
    container_name: 'redis'
    image:          redis:latest
    command:        ['redis-server', '--bind', 'redis', '--port', '6379']
    ports:
      - 6379:6379
    expose:
      - 6379

  account-service:
    image:          account
    depends_on:
      - redis
    environment:
      NODE_ENV:     development
      REDIS_HOST:   redis
    ports:
      - 3001:3001

  bank-service:
    image:          bank
    depends_on:
      - redis
    environment:
      NODE_ENV:     development
      REDIS_HOST:   redis
    ports:
      - 3002:3002

  lnd-service:
    image:          lnd
    depends_on:
      - redis
    environment:
      NODE_ENV:     development
      REDIS_HOST:   redis
    ports:
      - 3004:3004
